language: ruby
rvm:
  - 2.5.3
addons:
  postgresql: 9.6
before_script:
- psql -c 'create database lyricbunny_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake test
